### ISSUE TITLE
mailto: links

### ISSUE THREAD

**Issue by haasn** [wangp/bower#10]
I have a mailto: link containing a lot of extra metainformation (such as the subject and X-Reply-To headers), such as generated by a mailing list.

Would it be possible to have bower automatically parse these sorts of mailto: links when fed into the ‘To:’ field?

**Comment by wangp** [comment]
It's doable, and could be handy.

**Comment by wangp** [comment]
It's there now. Two of three browsers I tried don't provide a way to copy the mailto: link so it's not quite as useful as I imagined. It would be more useful if you could launch bower with the mailto: link as a command-line argument.

**Comment by haasn** [comment]
I gave it a try (ran into another mailto link the other day). When I click on the mailto link, I get a new blank tab that has the page URL set to this mailto link. I can simply copy the URL and paste it into the bower “To: ” prompt.

The catch is that I get the mailto: in URL-encoded form (which I believe is correct/expected behavior seeing as it's a URI), but bower does not parse/decode this correctly. Even if I cut out some of the problematic parts, bower will just interpret the `+`s as literal plus signs, and the `%0D%0A` as those literal character strings instead of newlines.

Would it be possible to also add URL decoding to this mailto handling? Then I could just directly paste them from my browser, even for more complicated mailto: templates.

**Comment by wangp** [comment]
It should work. Can you attach a test case?

**Comment by wangp** [comment]
RFC 6068 specifically warns about + standing for a space but we may have to budge on that.
