### ISSUE TITLE
searching for key using email should be case insensitive

### ISSUE THREAD

**Issue by craftyguy** [wangp/bower#102]
I've noticed that if I have a GPG key for a recipient `foo.bar@example.com`, but happen to reply to a mail where their email includes caps, e.g. `Foo.Bar@example.com`, bower fails to find the gpg key. If I lower the casing manually, it works. I don't think the email spec cares about caps in the address (e.g. sending a mail to both emails above should end up in the exact same inbox), so maybe bower should do a case-insensitive search for a matching key?

**Comment by wangp** [comment]
That makes sense. Please test the `gpg-key-ignore-case` branch.

**Comment by craftyguy** [comment]
@wangp works great, thanks for the quick fix :)
