### ISSUE TITLE
boolean AND search

### ISSUE THREAD

**Issue by jgarte** [wangp/bower#104]
1. How can I search for an email for two pieces of text?

I'd like to search for "important" and "Job" in the body of the email, for example.

2. How can I learn how to search for this type of information in the future?

Should I be reading the notmuch man pages mostly?

**Comment by wangp** [comment]
Yes `man notmuch-search-terms`.

Your example *should* be `body:(important job)`. However, that's currently preprocessed to `body: ( important job )` which isn't the same. I'll need to fix that.

**Comment by wangp** [comment]
I've fixed it on the `search-term-parser` branch.
