### ISSUE TITLE
mblaze written in mercury

### ISSUE THREAD

**Issue by jgarte** [wangp/bower#106]
Hi,

Maybe this is not the place for this. Should I ask on the mercury mailing list?

What do you think of creating a port of mblaze in mercury?

https://github.com/leahneukirchen/mblaze

Basically, various CLI tools for dealing with email in pure mercury.

It wouldn't depend on notmuch.

**Comment by jgarte** [comment]
For fun and to practice parsing/encoding/decoding [rfc2047](https://datatracker.ietf.org/doc/html/rfc2047), rfc2045, and rfc2231 with mercury?

Mostly just looking for some way to learn mercury that is practical for me.

**Comment by wangp** [comment]
Seems like a suitable project, go for it!

**Comment by jgarte** [comment]
Thanks for the encouragement! I might reach out on the mercury mailing list at some point. I have been meaning to do that and get more involved.
