### ISSUE TITLE
'r' in thread view should consider Reply-To Header

### ISSUE THREAD

**Issue by ff2000** [wangp/bower#12]
I know there is "L" and "e" bindings, but I happen to accidentally hit 'r'(eply) and just notice my error when the mail already was sent. Bad when a public mailing list post ends up as a private mail...
Probably there could be a logic like "use Reply-To header for 'To' if it is present and place sender to CC, otherwise use sender". At least Reply-To should be added to CC.

**Comment by wangp** [comment]
It sounds like the mailing list has set the Reply-To header to its own address.

'r' is for replying to the sender of the message only; it uses notmuch reply --reply-to=sender underneath. --reply-to=sender will prefer Reply-To over From unless it detects that the Reply-To header has been munged by the mailing list. This preserves the intention of a private reply.

To reply publicly you really need to use 'e' or 'L'. If you're not in the habit of sending stuff that you might regret, you can treat 'e' as your default (I think).

It *is* useful to be able to resend a message with minor edits. Mutt had a function like this. It occurred to me that it's almost exactly the same as recalling a postponed draft. I have quickly implemented it and will push it out after some more consideration.

**Comment by wangp** [comment]
You can now use 'E' to compose a new message from an existing message.
