### ISSUE TITLE
Reading FQDN from /etc/resolv.conf?

### ISSUE THREAD

**Issue by haasn** [wangp/bower#15]
This seems like a bug to me - or if not a bug, then I'm just wondering if it will cause my any problems.

For starters, what happens if you have multiple search domains in resolv.conf? What if you have a search domain that you're not actually a part of?

For example: Out of laziness, I included my university's domain in resolv.conf so I can just “connect foo” instead of “connect foo.informatik.uni-ulm.de”. Obviously, my local host is not part of my university's domain, yet due to this, bower still tries sending mails with `Message-ID: <...@nanodesu.informatik.uni-ulm.de>`.

Is this a bug; and will this cause me any problems or is the domain part of the Message-ID more or less arbitrary to begin with?

**Comment by wangp** [comment]
It won't cause problems as message IDs are essentially arbitrary.

The message ID generation is based on mutt. I see that the latest mutt no longer guesses the domain by reading /etc/resolv.conf. It was always a bit strange.

**Comment by wangp** [comment]
We now get the fqdn using gethostname, getaddrinfo on master.
