### ISSUE TITLE
[Request] Automatically set correct From address for reply

### ISSUE THREAD

**Issue by ber532k** [wangp/bower#25]
I prefer not to have a default account set in bower, so when I reply to some mail I received on any of my accounts, I get something like `From: myself@my_router` as the default, which obviously gets me nowhere and I manually have to change `From:` every time. Would it be possible to have the reply functionality check if `To:` in the received message is configured as an outgoing account for bower and then use this by default for the `From:` field, possibly just leaving it blank otherwise?

**Comment by wangp** [comment]
The reply template is constructed by "notmuch reply". I think the behaviour you want is mostly achieved by setting multiple addresses for `user.other_email` in `~/.notmuch-config`. If none of your configured addresses can be found in the message, it falls back to `user.primary_email` (which it makes up if unset).

**Comment by ber532k** [comment]
Works, thanks. I supposed bower constructed the template itself, so I apparently just looked in the wrong place. Feel free to close the issue.
