### ISSUE TITLE
[Request] Show message's sourcecode

### ISSUE THREAD

**Issue by ber532k** [wangp/bower#26]
It would be great if there was an easy way of displaying an email's source in bower. Currently, whenever I'm interested in what an email's source looks like, I fire up mutt, locate the message, display it and toggle weed off via `w`. It would be great if I could just press `w` (or some other key, if you like that better) in bower to just have the currently selected message displayed in some sort of pager in it's raw format.

`less <filename>` would certainly do the job and one could return to bower similar to how one returns from the text editor by simply exiting `less`.

**Comment by haasn** [comment]
You can use ‘V’ to navigate to the part in question and press ‘o’ to open it in e.g. vim (or less).

**Comment by ber532k** [comment]
I know, but that only opens the selected part, copied to some place in `/tmp`. It also messes with line breaks in some cases and most importantly I still can't inspect the original header. I was talking about displaying the original file in my maildir. Currently I can't seem to find any convenient way of looking up what's set as `Content-Type:` and `charset=`, for example. Sorry for the ambiguity.

**Comment by haasn** [comment]
Seems to work for me?

![example](https://0x0.st/7mB.png)

**Comment by ber532k** [comment]
Ups, sorry. I just missed that `V` was uppercase (and that this was different from what `v` does. Thanks for the help, I'll close the issue, then.
