### ISSUE TITLE
Formatting non-text parts other than HTML using external commands

### ISSUE THREAD

**Issue by aperezdc** [wangp/bower#33]
Currently it is already possible to use the `html_dump` option in the configuration file to convert HTML parts to plain text:

```ini
[command]
  html_dump = lynx ...
```

It would be super nice if it would be possible to specify how invoke filters to handle other MIME types, for example:

```ini
[filters]
  # Replaces the html_dump setting above.
  text/html = lynx ...

  # Prints .ics files to stdout as plain text.
  text/calendar = vcal -start -end -summary /dev/stdin

  # PDF files, too!
  application/pdf = pdftotext - -
```

**Comment by aperezdc** [comment]
Some moments ago I built Bower from the `filter` branch and seems to work like a charm. I'll keep using this build for the next days as well to give it some more testing.

Thanks a ton for looking into this — I would have liked to contribute a patch but Mercury is completely alien to me :innocent:

**Comment by wangp** [comment]
Actually, there's a potential deadlock if you're filtering large "text" parts as the pipe to the external process can fill up. So don't do that yet. (text/html is okay.)

**Comment by aperezdc** [comment]
So far I have tried only wit small parts under ~20 KiB, if I remember correctly. Let me know if I can help trying out things somehow.

**Comment by wangp** [comment]
I've pushed a fixed version to master. Enjoy.

**Comment by aperezdc** [comment]
JFTR, in case someone else arrives here: I have discovered that [khal](https://lostpackets.de/khal/) —which I was using already— can also print `.ics` files. Now I am using the following instead:

```ini
[filters]
  text/calendar = khal printics
```

I love this feature, thanks again @wangp for implementing it!
