### ISSUE TITLE
Enhancement: Passing configuration file as parameter and/or environment variable

### ISSUE THREAD

**Issue by rseichter** [wangp/bower#34]
I was surprised to see that the configuration file seems to be hardcoded as `~/.config/bower/bower.conf`. I would appreciate being able to use a command line parameter and/or an environment variable to specify different configuration files:

```
# Method 1
$ bower --config ~/.bowerrc

# Method 2
$ BOWER_CONFIG="/some/dir/bower.config" bower
```

**Comment by wangp** [comment]
I've added support for a BOWER_CONFIG environment variable. Also, the XDG base directory specification was previously supported but undocumented.
