### ISSUE TITLE
Parallel build not supported

### ISSUE THREAD

**Issue by rseichter** [wangp/bower#38]
I notice that parallel builds are not currently supported, and that the **PARALLEL** variable is even set to an empty string in `src/Makefile`. Is this deliberate? If I patch the Makefile, I can build using **--jobs 8** for a significant performance boost.

**Comment by wangp** [comment]
The user should specify the PARALLEL variable manually as demonstrated in the readme. We could automatically set a value based on the number of processors detected (with nproc, etc.) but it's not really necessary.

**Comment by rseichter** [comment]
Sorry @wangp , this one is on me. I only just noticed a typo in my Gentoo ebuild which caused the issue.
