### ISSUE TITLE
Support for "forwarding" an email?

### ISSUE THREAD

**Issue by dtzWill** [wangp/bower#39]
Popular feature, not sure how it's normally implemented but believe it's a reply of sorts, but with a modified subject (usually) and custom To/Cc headers.

Sorry if missing something :).  Would it be possible to add this feature? Comments on any anticipated implementation details (is it somehow not an easy task or otherwise problematic?) appreciated as well, so myself or others can add it instead.

Thanks!

**Comment by wangp** [comment]
There is a "bounce" (B) command if that helps.

I think the implementation of forward would be similar to reply. The notmuch CLI provides a subcommand to generate the reply template, but bower would need to generate forward templates itself. On the other hand, the main difficulty with replies is figuring out which addresses to reply to.

- Should the forward command include the original message (or just the main part?) as a message/rfc822 encapsulated message? How well are they handled by other MUAs? Bower doesn't allow you to create a nested tree of attachments normally so it'd be a special case.

- Or should the forward command copy the body text to create a new message? Too bad about HTML messages (use another MUA).

- Should attachments be included in the new message by default? The user can delete unwanted attachments before sending. The only downside I can think of is accidentally forwarding large attachments.

**Comment by wangp** [comment]
I have created a `forward` branch with the function bound to `W` in the thread view. The new message template will only be filled in from a `text/plain` part; trying to forward a HTML-only message will result in a blank template. Attachments will automatically be included in the new message.

A problem exists with encrypted messages. Manually decrypting (parts) in the thread view before pressing `W` won't work, those encrypted parts will still be skipped when making the new message. It should work better with automatic decryption (`decrypt_by_default = true`). Don't know if I'll fix it.

**Comment by wangp** [comment]
I've merged this as is. Thanks for testing.
