### ISSUE TITLE
GnuPG Support

### ISSUE THREAD

**Issue by haasn** [wangp/bower#4]
Is there any plan for adding direct support for e-mail encryption using GnuPG? Relevant features could include:

- Add an option/prompt (on the ‘sending’ screen) to encrypt the email, using GPG keys that match the e-mail address (display a list of them ideally)
- Detect encrypted messages sent to you and automatically prompt for decryption or add a decryption command
- Automatically verify attached signatures (and strip the uninteresting blocks)
- A shortcut to attaching your own public key to a message (for exchanging keys)

**Comment by haasn** [comment]
Can you merge master into crypto-testing (or rebase it)? I can't get the two to play together nicely on my end, which means I've been unable to receive updates from master.

**Comment by wangp** [comment]
Rebased. I only checked it compiles ;)

BTW, a few months ago I tried to implement verification. I got bogged down in UI issues (how to present failures/warnings in the limited space available). The preparsed message output from notmuch turned out to be unhelpful as well. Decryption might be easier: it decrypts or it doesn't.

**Comment by haasn** [comment]
Thanks, the rebase seems to work.

**Comment by haasn** [comment]
Decryption would be a really nice feature to have, too. I just had to manually save a file, gpg decrypt it, write my own base64 decoder to decode the attachment and then manually copy/paste the signature in order to verify it.

**Comment by haasn** [comment]
Hmm, and manually verifying a multipart message seems to be completely nontrivial, since I have to manually handle the decoded message as per RFC 3156.

Which I'll now have to go read, I guess.

**Comment by haasn** [comment]
(Would also like to point out that crypto-testing no longer merges cleanly with master, and as usual I'm not quite sure how to resolve the issues in src/compose.m)

**Comment by wangp** [comment]
I have rebased crypto-testing now.

Decryption should probably work just like text (un)folding and therefore present no UI issues.

**Comment by wangp** [comment]
The crypto-testing branch now supports decryption through notmuch. Press 'z' on an encrypted part to decrypt it.

The previous plan to perform decryption in bower itself would require parsing the decrypted RFC822-style output, something which notmuch did for us up to now. It doesn't make sense to create a completely separate code path just for encrypted messages.

The downside is that if bower and notmuch run on two different machines then encryption & signing will occur on one machine, and decryption & verification will occur on another. You would need working GPG setups on both machines, or else figure out how to forward gpg-agent from one to the other.

**Comment by haasn** [comment]
Seems reasonable to me. Glad to see more work on this being done!

Any chance to get support for signature verification as well? i.e. say my decrypted message contains both a message part and a signature part, I would like to verify the authenticity of said signature.

(Ideally verification should be done automatically, due to laziness otherwise defeating the point)

Also, trying to open parts of a decrypted message in a program (e.g. `vim`) just gives me a blank file (0C 0L).

**Comment by wangp** [comment]
Pushed:
* fixed signature generation (CR/LF issue)
* open/save decrypted part works
* manual signature verification with 'y' key (don't know why, we're running out of keys)
* options to encrypt/sign/decrypt/verify by default

I think it's pretty usable now. You can't postpone or recall encrypted/signed messages. I may or may not get around to it.

**Comment by haasn** [comment]
> I think it's pretty usable now.

I'd tend to agree. It's gotten the point where I'd be comfortable closing this issue if it gets merged into master.

**Comment by wangp** [comment]
You can now postpone and recall encrypted/signed messages.

I quickly added a warning about leaking the identities of Bcc recipients if encryption is enabled. It seems the safest fix would be to send separate messages to each Bcc recipient, but it's pretty low priority.

> One very minor suggestion I have is to display the key ID of signatures in addition to the name

In which context?

**Comment by haasn** [comment]
> In which context?

Well, for example for a signature that's part of an encrypted multipart message, I see something like `─• Good signature First Last <email@example.com>` but no key ID anywhere.

**Comment by wangp** [comment]
Can you try it now? For some reason notmuch does not provide the user id so I only see `Good signature fingerprint XXXXXXXXX`.

**Comment by haasn** [comment]
A user ID would be preferable at is the “de-facto standard” way of communicating IDs to humans. If notmuch does not provide that, I guess the right place to file this particular issue would be upstream?

Note that the fingerprint we have now is certainly adequate in terms of information: I can use `gpg --list-keys XXXXXXXXX` in order to see a listing of the associated keys (and their IDs).

**Comment by wangp** [comment]
> For some reason notmuch does not provide the user id

I meant to say, *my installation* of notmuch does not provide the user id for a good signature verification, but evidently it works for you.

**Comment by haasn** [comment]
Ah, I see now. Well, I guess then we should avoid trying to rely too much on one particular format and just give the user what notmuch outputs - and if we have concerns about the format itself, we should reach out to notmuch's code and change it there.

**Comment by wangp** [comment]
Merged crypto-testing to master.
