### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by ff2000** [wangp/bower#5]
I have different mail acounts for different purposes. Currently I can use bower only with one account if I have to send mails out.
In order to send mails with a specific account it is neccessary to specify different sendmail-calls, e.g. passing --account to msmtp. This would require support for multiple accounts in bower.
Replying to messages then sould chose the correct profile, of course.

**Comment by SergioBenitez** [comment]
I ran into this same issue, so I wrote a small Python script to solve the problem. I figured it might be useful to others, so I've made it available at [SergioBenitez/bower-send](https://github.com/SergioBenitez/bower-send).

**Comment by wangp** [comment]
Cool. If it's generally useful, it should not be hard to implement in bower directly.

**Comment by SergioBenitez** [comment]
That would be nice, @wangp. In particular, I would really like it if, when there are multiple configured accounts, Bower asked for a `from:` when composing a message. What would be even _cooler_ is if it let me select from multiple options (by pressing a key, say, `1`, `2`, etc), with one of the options being the default/primary account.

Also, while I'm on the feature request side of things, I think it would be great if pressing `~` implied previously pressing `l` for quicker entering of aliases. Not having to press `enter` when there's a match would be nice, too.

**Comment by wangp** [comment]
The ~ key seems like it could be slightly more convenient, so I added it. I didn't make it automatically accept a completion or anything like that.

**Comment by wangp** [comment]
I pushed the 'accounts' branch now. The configuration is similar to that in the bower-send README, but simpler. Let me know if it will work for you.

You can choose the account fairly easily on the compose screen by pressing 'f' to edit the From header, then pressing up. The history is pre-populated with your account addresses. (An alternative design was a key to cycle the From header through your accounts.)

There is a concept of a 'fallback' account that can be chosen if the From address does not match any other. I might rename that to 'default' as it's also used when the UI needs to fill in a From address with something.

**Comment by wangp** [comment]
I have merged the 'accounts' branch to master, except that the "fallback" account is now called a "default" account.
