### ISSUE TITLE
open attachment in background and tiling window manager

### ISSUE THREAD

**Issue by xunam** [wangp/bower#56]
Hello,

When opening an attachment in the background, using a command like `xdg-open&`, and the terminal resizes, it seems that this resize event is mistaken for a keypress and the attachment file is deleted, which might happen too fast for the opening application to grab the file.

A few details on my setup: I use a tiling window manager (dwm) and often open PDF files from attachments (using zathura). When the viewer opens its window, the terminal that holds bower (st with or without tmux) gets resized, then the viewer is blank and the PDF has vanished.

Unfortunately I do not know enough Mercury to try and make a patch myself…

**Comment by wangp** [comment]
Thanks, I think it should be fixed now.

**Comment by xunam** [comment]
Indeed, it works now. Thanks for your efficiency!
