### ISSUE TITLE
Thread pane is too small

### ISSUE THREAD

**Issue by csabahenk** [wangp/bower#60]
I see the size of the thread pane is hard-coded to be capped at 8. That's a miserable user experience when trying to find my way through a lengthy thread on my hidpi screen.

I could get as far by myself  as to change the value of `max_thread_lines` in _thread_pager.m_ from 8 to 80 (that's about half of my terminal height), but I think a more complete solution would be desirable, involving some of the following possibilities:

- make it a config option
- instead having a hard-coded cap, make it proportional to the terminal size
- allow the thread pane be interactively resized with keys

**Comment by seifferth** [comment]
@csabahenk I just made a pull request for one possible solution. Maybe you could drop me a quick note if this would work for you.

**Comment by wangp** [comment]
Hopefully good enough now.
