### ISSUE TITLE
Compiler version

### ISSUE THREAD

**Issue by seifferth** [wangp/bower#64]
Which version of the mercury compiler does bower currently require? I see `NEWS` said 14.04 at some point, but was reverted to say 14.01. I myself experienced issues building with 14.01 on Arch Linux, but building with mercury 20.06 works just fine.

**Comment by wangp** [comment]
There was never a Mercury 14.04 release, so that was a typo. I'm not sure why 14.01 didn't work for you. If you happen to have the logs then I could take a look, but it doesn't really matter.

**Comment by seifferth** [comment]
Thanks for clarifying. I don't think I have retained any logs. But then, Arch Linux is supposed to be a cutting edge distribution anyway, so I guess I'm happy enough that it builds with mercury 20.06.
