### ISSUE TITLE
[Key binding] `N` isn't search backward

### ISSUE THREAD

**Issue by seifferth** [wangp/bower#70]
The usual convention would be to use `n` for next search result and `N` for previous search result. If I happen to jump past the result I was looking for, I end up marking a message unread quite often. Maybe we could toggle messages **U**nread, rather than toggling them **N**ew? This would free `N` for previous search result.

I realise that this change might feel unnecessary for others, so I wanted to discuss it here before working on it. I'd be happy to implement it if my proposal is accepted.

**Comment by wangp** [comment]
I think I'd be okay with moving `n` to `U`. It does match the notmuch tag `unread` and the `~U` search term macro.

I also had a quick try at displaying new threads/messages with `u` instead of `n` but it looked weird...

**Comment by wangp** [comment]
Merged.
