### ISSUE TITLE
lost 'name="signature.asc"' recently (see #52)

### ISSUE THREAD

**Issue by dtzWill** [wangp/bower#74]
Cleanup in d0cd94026cf13a90e4fa2e67065b86b03e2c310f seems to have lost the fix for #52 :(.

Could this be restored?

----

Would it make sense to also include a "Content-Disposition" one way or the other (attachment vs inline), like `Content-Disposition: attachment; filename="signature.asc"`?

Between reading the RFC's and quick-sampling notmuch/astroid/xapian/etc. test mail corpi (corpus-es) +my own mail, I'm not sure what behavior is really best here.  So maybe nevermind on this aspect :).  Mentioning because maybe (maybe!) adding such a line is easier than plumbing support for parameters or something, but not sure it can replace adding `name="signature.asc"` to the "Content-Type" line as done previously.

----

Anyway, thanks for all your work!
(can't wait to rebuild with the latest goodness like alt+key support!! :D)

**Comment by wangp** [comment]
Oops, thanks for the notice. Fixed now.

Let me know if you figure out the `Content-Disposition` matter.

**Comment by dtzWill** [comment]
Thank you! Much appreciated!
Will let you know if I sort out or find evidence that Content-Disposition is important to be set some particular way for some use cases we care about.

Take care!
