### ISSUE TITLE
Any way to alias key bindings to other things?

### ISSUE THREAD

**Issue by xxxserxxx** [wangp/bower#78]
The sample config doesn't have a custom key binding example. Is this possible?  

For example, mapping a key to `'+ +spam +deleted -inbox -unread` to bulk tag selected emails as spam and get them out of the inbox.

**Comment by wangp** [comment]
No, nothing like that has been implemented.

**Comment by xxxserxxx** [comment]
Ok, thanks. It's easy enough to do externally.
