### ISSUE TITLE
[feature request] Autocrypt support

### ISSUE THREAD

**Issue by xxxserxxx** [wangp/bower#82]
[Autocrypt is a specification](https://autocrypt.org/) for email clients to negotiate email encryption. For Bower, it'd be adding a header that communicates encryption preferences, and then code to recognize the header and automatically set the encryption preferences for that address. The benefit of this is that it allows per-destination address encryption settings, rather than one global setting.

Autocrypt is supported in a number of email clients, including K-9 (Android), Enigmail, Mutt, Neomutt, and Balsa.

One option would be to not add a config option, but set the Autocrypt header based on whether the user configured PGP settings.

**Comment by dtzWill** [comment]
FWIW also mentioned/suggested in #67, just to keep discussion together :).

**Comment by xxxserxxx** [comment]
Sorry, I missed that one.
