### ISSUE TITLE
[feature request] accept mailto: on cmdline

### ISSUE THREAD

**Issue by craftyguy** [wangp/bower#86]
I found https://github.com/wangp/bower/issues/10, but think it would be useful for bower to accept mailto: links as a cmdline option. aerc (another mail client) does this, and it's super handy.

**Comment by wangp** [comment]
I've implemented this on the `mailto-cmd-line` branch.

**Comment by craftyguy** [comment]
@wangp I just gave it a try, and it works great when the mailto: has only the email address specified and no other data that it could contain from a html href link. 

The use case I had in mind here is a browser (like firefox) calling bower with the mailto: passed to it from the href mailto when I click on a link on some site. These can contain a subject and/or a body too in url query form:

```
mailto:foo@example.com?subject=Bower is a great mail app
```

```
mailto:foo@example.com?subject=Bower is a great mail app&body=No really, you should try it out!
```

I think it can even contain CC and BCC fields too. With your current branch, if any of these extra fields are specified, bower fails:

```
$  ./bower "mailto:foo@example.com?subject=Bower is a great mail app"
Error parsing mailto: argument.
```

I think supporting some of the fields (like subject and body) would be great, but if you don't want to do that now then what do you think about having bower just print some message about unsupported fields that it'll ignore, but still open the compose view with the To: email added (and not error out completely as it does now) ?

**Comment by craftyguy** [comment]
hmm, ok it seems like it actually does handle those fields, I'm not sure why my initial test of that failed.

**Comment by wangp** [comment]
Thanks for testing. Merged to master.
