### ISSUE TITLE
[feature request] configurable address book: khard

### ISSUE THREAD

**Issue by jgarte** [wangp/bower#88]
Hi is there currently a way to set khard as my address book?

I'm thinking of something like this:
https://github.com/ninewise/dotfiles/blob/09cfde6d20e12e5dd67fe2a3a35ec81260d5d088/config/alot/config#L30

**Comment by wangp** [comment]
No, the address book functionality is not configurable (yet?)

**Comment by jgarte** [comment]
btw, I started maintaining the bower package in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/mailreaders/notmuch-bower/default.nix).

I'm planning to package bower soon for [GNU Guix System](https://guix.gnu.org). 

I'll let you know once it's been accepted in upstream.

@wangp Have you tried running/testing bower on a 32bit machine yet?

**Comment by wangp** [comment]
Cool.

Yes, I run bower on a Raspberry Pi 3B (in 32-bit mode), and previously on a SheevaPlug.

**Comment by jgarte** [comment]
> No, the address book functionality is not configurable (yet?)

I just re-read [this](https://github.com/wangp/bower#simple-address-book) and learned how to use [notmuch address](https://notmuchmail.org/manpages/notmuch-address-1/). 

nm about khard ;) 

Unless someone else wants that functionality...
