### ISSUE TITLE
test_process failing on Alpine Linux

### ISSUE THREAD

**Issue by craftyguy** [wangp/bower#89]
I recently packaged bower on Alpine Linux, and now the `test_process` test is failing with "unexpected output"

I patched the test to show the expected output at the end for comparison, both are in this file:

[test_process.out.txt](https://github.com/wangp/bower/files/6927456/test_process.out.txt)

There's a difference. From what I understand (I don't know mercury..), the test appears to be writing 64K bytes to a pipe and reading it back from the other end.

This test did pass in the CI[1], so it's a little confusing as to why it's failing on the build servers[2]

1. https://gitlab.alpinelinux.org/craftyguy/aports/-/jobs/453943#L726
2. https://build.alpinelinux.org/buildlogs/build-edge-aarch64/testing/bower/bower-0.13-r0.log

I'm not really sure how to proceed with debugging this further, so if you have any advice it would be greatly appreciated.

**Comment by wangp** [comment]
I wasn't able to reproduce it in a Alpine 3.13 chroot.
I'll test it in a VM some time. Perhaps it's specific to aarch64.

**Comment by craftyguy** [comment]
No, not specific to aarch64, it's failing on x86/x86_64 too.

This was run on Alpine Edge (the rolling release)

**Comment by wangp** [comment]
There is a bug in the `rev` program on Alpine Edge.
```
alpine:~/bower/tests# wc -c input.txt 
260 input.txt
alpine:~/bower/tests# rev < input.txt | wc -c
515
```
I've attached the input file. Do you mind reporting it to the Alpine developers?
[input.txt](https://github.com/wangp/bower/files/6948523/input.txt)

**Comment by craftyguy** [comment]
ah interesting! I don't mind reporting it, thanks for tracking it down to this.

**Comment by craftyguy** [comment]
Looks like a bug in busybox. util-linux from kernel.org works. (I tried to propose a fix here, but I'll work with the upstream busybox folks on it.. http://lists.busybox.net/pipermail/busybox/2021-August/089016.html) 

Thanks again for the help with this.
