### ISSUE TITLE
Weird behavior when dealing with \ characters in headers

### ISSUE THREAD

**Issue by haasn** [wangp/bower#9]
Not sure exactly which components are affected in which way, but here are some results. First off, I sent myself an e-mail like this:
```
From: "foo \n bar" <wao0Hech3h@nand.wakku.to>
To: quahtieN8a@nand.wakku.to
Cc:
Bcc:
Subject: testing stuff \n foo
Reply-To:
In-Reply-To:

foo \n bar
```

During sending, it seems to turn the "foo \\n bar" into "foo n bar", since that's what the resulting e-mail contains. Not sure which components is doing this.

Furthermore, I've received an e-mail like this:
```
...
From: "\\n" <email@redacted>
...
```

In the bower index, this displays the involved participants as “\\n, nand” (the latter being me), and in the e-mail view it shows “From: \\\\n <email@redacted>” (and lists the author as “\\\\n” in the subject line). I'm also not sure which component is causing this inconsistency.

**Comment by wangp** [comment]
> During sending, it seems to turn the "foo \n bar" into "foo n bar", since that's what the resulting e-mail contains. 

You'll need to escape the backslash when you enter it.

It's not ideal. Bower needs to be able to parse an address or addresses when you enter them, and the obvious format for that is the address list format of RFC 822-type messages (even if that is a transport format, not generally for end users). After you enter it, the address list is parsed in a lenient way and canonicalised. "\n" is canonicalised to "n".

Perhaps backslash should only escape a subsequent backslash or double quote. The compose screen should *display* address lists in human-friendly form (without extra quotes and backslashes).

> In the bower index, this displays the involved participants as “\n, nand” (the latter being me), and in the e-mail view it shows “From: \\n email@redacted” (and lists the author as “\\n” in the subject line). I'm also not sure which component is causing this inconsistency.

This looks like a bug in notmuch show --format=json

**Comment by haasn** [comment]
> Perhaps backslash should only escape a subsequent backslash or double quote.

I think this might make sense - after all, the interface here is one that users are expected to work with. I would agree with backslash only escaping another backslash or quote.

**Comment by wangp** [comment]
> Perhaps backslash should only escape a subsequent backslash or double quote. The compose screen should display address lists in human-friendly form (without extra quotes and backslashes).

Done those.
