### ISSUE TITLE
Exit bower from Thread view (Close all views and quit)

### ISSUE THREAD

**Issue by jgarte** [wangp/bower#90]
Is there currently a way to exit bower from the thread view or to close all views and quit?

[Tig](https://github.com/jonas/tig) has `Q`, for example:

https://github.com/jonas/tig/blob/d1096134319e738665f30f12519bd6e677d6d12f/test/help/all-keybindings-test.expected#L29

**Comment by wangp** [comment]
No, but it would not be hard to add to the thread view (in particular). Do you think there is reason to? Hitting `q q` seems easy enough to me (or even ^C if you have no tag changes). The only difference is that returning to the index view after a while may immediately incur a call to notmuch to check for new messages.

**Comment by jgarte** [comment]
I hadn't tried `^C`. Thanks for sharing that.

`^C` works for me :)

I'll close this now.

If someone else would like this feature feel free to reopen for more discussion.
