### ISSUE TITLE
in-line PGP not supported?

### ISSUE THREAD

**Issue by craftyguy** [wangp/bower#92]
I received an in-line PGP encrypted mail, and the main body/text was not decrypted, so I assume this is not supported in bower? If that assertion is true, would it be too difficult to add support for it? Obviously PGP/MIME is preferred, but apparently some folks are still using in-line PGP, and there's no way to save the encrypted mail content in bower to decrypt it manually, so I've been copying/pasting/decrypting the contents (which is annoying)

**Comment by wangp** [comment]
Decryption is handled by notmuch, and notmuch doesn't support inline PGP.

**Comment by craftyguy** [comment]
I see, thanks for clarifying!
