### ISSUE TITLE
Highlight Gemini Protocol URLs in Email

### ISSUE THREAD

**Issue by jgarte** [wangp/bower#96]
![2022-01-11-110619_1600x900_scrot](https://user-images.githubusercontent.com/47760695/148978551-6e59fd4d-c263-453b-a5a0-03aefb71c2ed.png)

**Comment by jgarte** [comment]
@wangp 

Where could I start looking in the bower code base if I'd like to make a PR to add this? 

I'm a bit lost at the moment.

**Comment by wangp** [comment]
Yes `detect_url_2` should succeed if it detects a URL in `String` after index `BeginAt`, where `Start` and `End` are the start and end indexes of the URL in `String`. A starting point would be to search for "gemini" with `string_util.unsafe_strstr` and go from there. However, I would be unhappy with scanning each string twice.

**Comment by Juliaria08** [comment]
> Yes `detect_url_2` should succeed if it detects a URL in `String` after index `BeginAt`, where `Start` and `End` are the start and end indexes of the URL in `String`. A starting point would be to search for "gemini" with `string_util.unsafe_strstr` and go from there. However, I would be unhappy with scanning each string twice.

Is there a way to see if it's in an array of elements? I'm not sure, and don't know mercurial. I don't think this would be a good idea as we're just hardcoding the valid schemes, whilst there's a RFC for schemes.

Wouldn't modifying the check to make it highlight any [valid URI](https://datatracker.ietf.org/doc/html/rfc3986#section-3) that follows the [RFC 3986's Scheme](https://datatracker.ietf.org/doc/html/rfc3986#section-3.1) be a better idea?
Such that every scheme is not needed to be hardcoded.

**Comment by wangp** [comment]
We should use a multi-string search algorithm. It's probably easiest to use the POSIX regex functions to search for `http|gemini`. I don't see any need to highlight all possible URIs; in fact I'd prefer it did not. I can't remember ever wanting to open any URI other than http(s) straight from the mail client.
