### ISSUE TITLE
Import mbox directly into bower

### ISSUE THREAD

**Issue by jgarte** [wangp/bower#98]
Hi,

Someone sent an [attachment](https://lists.sr.ht/~whereiseveryone/guixrus/%3C35nMZK-FJWB4yz0RuGSKmfa-y8w5ft2593kp-Fwc-KtcvReobUBMCpuAuUpu45fdok8ZgwV3FGuKWQ9RedWj3GjZfbenrnPQxaxIlt4yPG0%3D%40protonmail.com%3E/raw) to our [public inbox](https://lists.sr.ht/~whereiseveryone/guixrus/%3C35nMZK-FJWB4yz0RuGSKmfa-y8w5ft2593kp-Fwc-KtcvReobUBMCpuAuUpu45fdok8ZgwV3FGuKWQ9RedWj3GjZfbenrnPQxaxIlt4yPG0%3D%40protonmail.com%3E). 

Does anyone happen to know if there is a convenient way to import this into bower? Should it be imported with notmuch instead?

Any advice is much appreciated.

**Comment by wangp** [comment]
Normally you would split out a mbox into separate Maildir messages, then run `notmuch new`. But that attachment looks like a single message only, so you should be able to add it to your Maildir with `notmuch insert`.

**Comment by jgarte** [comment]
Thank you very much! that's exactly what I needed :)
